---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

library(data.table)

```{r echo = TRUE}

x <- read.csv("activity.csv")

```

## What is mean total number of steps taken per day?

```{r echo = TRUE}

stepsPerDay <- tapply(x$steps, x$date, sum, na.rm=TRUE)

meanStepsPerDay <-  mean(stepsPerDay, na.rm = TRUE)
meanStepsPerDay

medianStepsPerDay <- median(stepsPerDay, na.rm = TRUE)
medianStepsPerDay

steps = 0

for (i in 1:length(stepsPerDay)){
  steps <- c(steps, rep(i, stepsPerDay[i]))
  
}

hist( steps, xlab="Day", ylab="Steps", breaks=length(stepsPerDay))

```

## What is the average daily activity pattern?

```{r echo = TRUE}
intervalAvg <-  tapply(x$steps, x$interval, mean, na.rm=TRUE)

interval <- x[1:288, "interval"]

plot(x=interval, y=intervalAvg, type="l", xlab="Interval", ylab="Steps")

maxIntervali <- which.max(intervalAvg)
maxInterval <- intervalAvg[maxIntervali]
maxInterval

```

## Imputing missing values

```{r echo = TRUE}

sumMissingValues <- sum( is.na(x[, "steps"]) == 1)
sumMissingValues

xnew <- x

for (i in 1:length(x$steps)){
  
  if ( is.na(x[i, "steps"]) ){
    xnew[i, "steps"] <- intervalAvg [which(names(intervalAvg) == x[i, "interval"])]
  }
}


stepsPerDayN <- tapply(xnew$steps, xnew$date, sum, na.rm=TRUE)

meanStepsPerDayN <-  mean(stepsPerDayN, na.rm = TRUE)
meanStepsPerDayN

medianStepsPerDayN <- median(stepsPerDayN, na.rm = TRUE)
medianStepsPerDayN

steps = 0

for (i in 1:length(stepsPerDayN)){
  steps <- c(steps, rep(i, stepsPerDayN[i]))
}

hist( steps, xlab="Day", ylab="Steps", breaks=length(stepsPerDayN))

### Imputing NA values with average step for same interval significantly raised daily steps per day where the day 
### had NA values


```

## Are there differences in activity patterns between weekdays and weekends?

```{r echo = TRUE}

xnew$weekday <- weekdays( as.Date (xnew[, "date"]))

xnew$daytype <- factor( ifelse (xnew[, "weekday"] == "Saturday" |  xnew[, "weekday"] == "Sunday", "Weekend", "Weekday") )

xnew <- xnew[, -5]

y <- aggregate(steps~daytype+interval, xnew, mean)

par(mfcol=c(2,1))

plot(interval, y[ y[, "daytype"] == "Weekday", "steps"], main="Average steps on weekdays", type="l")
plot(interval, y[ y[, "daytype"] == "Weekend", "steps"], main="Average steps on weekends", type="l")

```
